# -*- mode: python ; coding: utf-8 -*-


block_cipher = None

exs=[
	"FLAC",
	"Ogg",
	"Opus",
	"OpusFile",
	"SDL2",
	"SDL2_image",
	"SDL2_mixer",
	"SDL2_ttf",
	"caio",
	"cv2",
	"ffpyplayer",
	"kivy",
	"kiwisolver",
	"libSDL2-2.0.0.dylib",
	"libSDL2_mixer-2.0.0.dylib",
	"libass.9.dylib",
	"libavcodec.58.54.100.dylib",
	"libavcodec.58.91.100.dylib",
	"libavdevice.58.10.100.dylib",
	"libavfilter.7.85.100.dylib",
	"libavformat.58.29.100.dylib",
	"libavformat.58.45.100.dylib",
	"libavresample.4.0.0.dylib",
	"libavutil.56.31.100.dylib",
	"libavutil.56.51.100.dylib",
	"libbluray.2.dylib",
	"libfreetype.6.dylib",
	"libfribidi.0.dylib",
	"libmp3lame.0.dylib",
	"libmpdec.3.dylib",
	"libogg.0.dylib",
	"libopenblas.0.dylib",
	"libopus.0.dylib",
	"libvorbis.0.dylib",
	"libvorbisenc.2.dylib",
	"libvorbisfile.3.dylib",
	"libwebp.7.dylib",
	"libwebpdemux.2.dylib",
	"libwebpmux.3.dylib",
	"libx264.160.dylib",
	"libx265.192.dylib",
	"matplotlib",
	"mpg123",
	"multidict",
	"numba",
	"numpy",
	"objc",
	"pandas",
	"psutil",
	"scipy"

]

a = Analysis(['doodah_s.py'],
             pathex=['/Volumes/home/ymq/pydev/github/ahserver/doodah'],
             binaries=[],
             datas=[],
             hiddenimports=[
				"multidict"
			 ],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[
				"FLAC",
				"Ogg",
				"Opus",
				"OpusFile",
				"SDL2",
				"SDL2_image",
				"SDL2_mixer",
				"SDL2_ttf",
				"cv2",
				"ffpyplayer",
				"kivy",
				"matplotlib",
				"mpg123",
				"numba",
				"numpy",
				"objc",
				"pandas",
				"psutil",
				"scipy"
			 ],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='doodah_s',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
